[tox]
envlist =
    py39-django32
    py39-django42
    py313-django52
isolated_build = false

[testenv]
deps =
    django32: Django==3.2.*
    django42: Django==4.2.*
    django52: Django==5.2.*
commands =
    python manage.py test